### ISSUE TITLE
Links-Rails_Cobbler-Ntedit - Setup parameters

### ISSUE THREAD

**Issue by AMMMachado** [bcgsc/LINKS#56] opened 2021-01-27 13:18 UTC
Hi @warrenlr,

First of all thank for the amazing softwares that you and your team have developing.If possible we need some advices about the using of BSCG softwares in our pipelines. 

We are working with several genomes, from fish's until mammals with high levels of heterozigoties and repeats.To mitigate these characteristics we have sequenced pacbio Hifi ccs datasets and short reads PE 250 (unfortunately the datasets are from different individuals). 
Now we are trying to integrate and use both datasets to improve the base assembly. 

Briefly, We have produced a Pacbio Hifi assembly with hifiasm (contig N50,3mb). 
In addition we have produced others assemblies (of the same pacbio dataset with different parameters). 
Next, we have produced 3 short read  assemblies from 250 PE datasets (average 8kb N50).
Now we are thinking if would be possible to integrate all datasets with the following strategy. 

1st - Links
Scaffolding of the base assembly with short reads assemblies. 
Below, you can find the parameters. These parameter were obtained from your previously study (https://www.mdpi.com/2073-4425/8/12/378/html). 

LINKS -f Assembly.fa -s PE250Drafts.txt -k 26 -l 5 -a 0.3 -d 1000,2500,5000,7500,10000,12500,15000,20000 -t 10,5,5,4,4,3,3,2

Regarding the -a, 0.3 , its  suitable for our purposes or should we increase it the values of 0.7 or 0,9 ?  
Are the remaining parameters adequate ? The links only perform the scaffolding or introduce some content in the assembly? ( as both datasets are from different individuals, in this step we would like to produce scaffolding without introduce "new nucleotide content").

2nd -  Rails & CobblerRe-scaffolding and gap-closing the assembly of step one, with the remaining pacbio assemblies.

runRAILSminimap.sh Assembly_PE250.fa Other_Assemblies.fa 2000 0.95 0 5 nil

3rd- Rails & CobblerRe-scaffolding and gap-closing the assembly of step two, with the pacbio raw reads.

runRAILSminimap.sh Assembly_PE250_Others.fa CCS.fa 2000 0.95 0 2 pacbio

Are the parameter adequate in step 2 and 3?
Once we are working with ccs reads and assemblies we have have set the max. softclip to 0 in the  2 and 3 we. Should we increase or decrease the Minimum sequence identity fraction? 

4 - ntEdit ntEdit to polish the final assembly with pacbio reads. 

Thank you in advance,
André

**Comment by warrenlr** [comment] 2021-01-27 15:41
Hello André and thank you for your interest in our tools.

There's a lot of info here, so I hope to break it down for you into clear advice.

`To mitigate these characteristics we have sequenced pacbio Hifi ccs datasets and short reads PE 250 (unfortunately the datasets are from different individuals)`

That's perfect for scaffolding or re-scaffolding strategies, as long as the genome structure is the same as that of your target genome (the one you are rescaffolding). 

Please see my comments below. Hope it helps
René

=========

`1st - Links
Scaffolding of the base assembly with short reads assemblies.
Below, you can find the parameters. These parameter were obtained from your previously study (https://www.mdpi.com/2073-4425/8/12/378/html).

LINKS -f Assembly.fa -s PE250Drafts.txt -k 26 -l 5 -a 0.3 -d 1000,2500,5000,7500,10000,12500,15000,20000 -t 10,5,5,4,4,3,3,2

`

LINKS does support multi intervals (-d), as you indicated. HOWEVER, this may not work with large mammalian genomes, depending on resource requirements (influenced by -t) and your system.  My suggestion is to first run the demo. Once it works, run -d 1000 -t 100 (single iteration) and measure the RAM usage. Then, adjust -t accordingly (if you have memory errors, increase -t. If not, you could decrease it to extract more kmer-pairs from your long reads). If your genomes are small (<=100Mbp), you may be able to run the iterative process natively, as you have it written down, again depending on your system's resources. Other wise, you may run iteratively by using the output of -d 1000 as input for the next -d run. 

`Regarding the -a, 0.3 , its suitable for our purposes or should we increase it the values of 0.7 or 0,9 ?`

-a 0.3 is more strict. I means that for each fork where there's multiple paths, the number of kmer pairs support from the second-best supported path is NO GREATER that 30% of the most supported path. If it is, NO scaffolding will ensue.  You can experiment with this parameter, setting it to a value you feel comfortable with. The higher you go, the more contiguous the resulting assemblies (& the higher the missassemblies).

`Are the remaining parameters adequate ? The links only perform the scaffolding or introduce some content in the assembly? ( as both datasets are from different individuals, in this step we would like to produce scaffolding without introduce "new nucleotide content").`

Yes, parameters look ok.  Please make sure you read the docs carefully on how to set. For reference-based scaffolding, you may wish to consider ntJoin, which is faster, lighter and less params to set (see comment below). LINKS/ntJoin will NOT introduce new bases (only scaffolding, but with "Ns" where a gap is created from scaffolding).


`2nd - Rails & CobblerRe-scaffolding and gap-closing the assembly of step one, with the remaining pacbio assemblies.

runRAILSminimap.sh Assembly_PE250.fa Other_Assemblies.fa 2000 0.95 0 5 nil

3rd- Rails & CobblerRe-scaffolding and gap-closing the assembly of step two, with the pacbio raw reads.

runRAILSminimap.sh Assembly_PE250_Others.fa CCS.fa 2000 0.95 0 2 pacbio

Are the parameter adequate in step 2 and 3?`

Difficult for me to say. Depends on many factors like long sequence data coverage, base accuracy, length distribution, etc.  I find 2000bp anchoring a strict requirement, but you can start there and see what you get and adjust accordingly. Also, a "0" soft clip is strict.. but you should try and see. For (2), I recommend you try ntJoin (https://github.com/bcgsc/ntJoin), our reference-based scaffolder. You can always fill gaps with ABySS-Sealer.

`Once we are working with ccs reads and assemblies we have have set the max. softclip to 0 in the 2 and 3 we. Should we increase or decrease the Minimum sequence identity fraction?`

Also difficult to say without knowing more about the data specs. This is definitely a parameter you should experiment with.

`4 - ntEdit ntEdit to polish the final assembly with pacbio reads.`

For polishing, it is important to use the same source of read as that of the assembly (i.e. not from a different individual). That's because if you don't do that, you will end up changing your draft assembly bases when there are SNPs. It might be a desired results, but I thought I should mention it.  Also, ntEdit can polish a wide range of assemblies (SMS, short, etc), but using high base accuracy reads (such as Illumina's). If your pacbio hifi reads have really high base accuracy (>99%) then it is fine to use but you may get unpredictable results if you try polishing an assembly with erroneous long reads, which is not the typical use case of ntEdit.

**Comment by AMMMachado** [comment] 2021-01-29 17:41
Hi @warrenlr,

Thank you so much for the speedy response and valuable inputs. 
We are testing all software following your advices.
This genome in specific it's from a marine fish with high heterozigoty. 

In terms of installations, Links, Rails and cobbler and ntedit are working perfectly, however we have some problems with the ntJoins when more than 1 reference are inputed.
The ntJoin github already have some issues describing the same pattern.
At local level, no problems were observed with > 1 reference.
However, we are working in HPC using singularity containers to install softwares.
The "quay.io/biocontainers/ntjoin" link was used to produce the singularity container.
Maybe we should open an issue in ntjoin github. 

We are really excited with ntJoin software.
It's really fast, and allow us to perform a lot of different tests at the same time.
Can you clarify the role of "reference_weights" in the software. From what i understood , is the importance/order of the assemblies to be used.  
Can/should we set both references types (Pacbio based / short read based) in the same run or in sequential/separeted runs?
The drafts assemblies should be provided together in a single file  (e.g Option 1 - references='Cat_All_Draft_Assemblies.fa' reference_weights='2'), or separated (e.g Option 2 - references='A.fa B.fa' reference_weights='2 2')?  
We have done these tests and the results are quite different.
Option 1 -  components in graph: 1698 ; 73mb of 815mb assigned.scaffolds (improve of n50, 200kb) .
Option 2 -  components in graph: 922 ; 47mb of 815mb assigned.scaffolds (improve of n50, 100kb) .
Are the low values of the assigned.scaffolds expected ?

The Links for some tests with -a 0.9/0.7 parameters seems to be very slow and time consuming.
The links has some multithread option to improve the speed (in our hpc, memory is not an issue)?
Comparing ntJoin with Links, do you see any advantage of use links instead of ntJoin for rescaffolding?
 
The rails/cobbler only performed improvements in the genome assembly when the ccs reads were inputted.
No improvements were observed with pacbio or short read assemblies as input. 
However was very effective in close gaps.

We are moving our approach to: 
scaffolding with ntJoin (inputs : pacbio and short read assemblies); all together  or sequentially ? 
rescaffolding/gapclosing with rails/cobbler (inputs : ccs reads)
polishing with ntedit (input : ccs reads)

Thank you again and sorry for boring you with all of this questions. 

André

**Comment by warrenlr** [comment] 2021-01-29 18:06
```
The Links for some tests with -a 0.9/0.7 parameters seems to be very slow and time consuming.
```

If you re-run LINKS in the SAME working directory and the same command but adjusting -a and -l, you can explore the effect of links ratios and min. links support very fast (would take only a few seconds to few minutes depending on genome size.  You would just have to copy the output with a new name to track the changes.

```The links has some multithread option to improve the speed (in our hpc, memory is not an issue)?```

LINKS is not multithreaded, but we are working on porting the code to C++ (we should have a version in a few weeks/months)


```Comparing ntJoin with Links, do you see any advantage of use links instead of ntJoin for rescaffolding?```

Although you can use both for reference-based scaffolding, LINKS was designed for scaffolding with error-rich nanopore reads. As you pointed out, ntJoin is much faster and efficient and you have done the work of generating additional assemblies, which can be used for scaffolding.  LINKS will work best with high-coverage, whereas ntJoin can make use of a single "reference" or draft assembly (eg. 1X).

```The rails/cobbler only performed improvements in the genome assembly when the ccs reads were inputted.
No improvements were observed with pacbio or short read assemblies as input.
However was very effective in close gaps.```

Because it is using minimap2 alignments, in our experience we found it useful to "break" input assemblies into overlapping 2500, 5000 and 10000 bp sequences (you can generate any combinations and run pooled or iteratively) before running RAILS/cobbler.  This will ensure good anchoring alignments to sequences flanking gaps and should see better gap-filling yield.

```
We are moving our approach to:
scaffolding with ntJoin (inputs : pacbio and short read assemblies); all together or sequentially ?
```

We find ntJoin to work better when running iteratively, as opposed to providing multiple references. This is because there may exist conflicts between the provided references that prevent unambiguous joins.

Regarding your other ntJoin question, I will let ntJoin developer @lcoombe comment.

All the best and thank you for using our tools! If you like, please star our projects ;)

**Comment by AMMMachado** [comment] 2021-02-01 13:30
Hi @warrenlr and @lcoombe ,

Links
Thank you for the useful informations about Links. 
We will focus our pipelines in ntJoin, at least for this specific project. 

Rails/Cobbler

  ""break" input assemblies into overlapping 2500, 5000 and 10000 bp sequences"  means to merge all assemblies and collect all sequences of 2500, 50000, 10000 to three independent files, or really break the contigs in sub-sequences of 2500, 50000, 10000  and run them (pooled or interactively) against the reference ? 

NtJoin - Update 

"In terms of installations, Links, Rails and cobbler and ntedit are working perfectly, however we have some problems with the ntJoins when more than 1 reference are inputed.
The ntJoin github already have some issues describing the same pattern.
At local level, no problems were observed with > 1 reference.
However, we are working in HPC using singularity containers to install softwares.
The "quay.io/biocontainers/ntjoin" link was used to produce the singularity container.
Maybe we should open an issue in ntjoin github."

We have solved this problem, and now NtJoin is working properly. 

Can you clarify the role of "reference_weights" in the software. From what i understood , it is the importance/order of the assemblies to be used.

Can/should we set both references types (Pacbio based / short read based) in the same run or in sequential / separeted runs?

The drafts assemblies should be provided together in a single file (e.g Option 1 - references='Cat_All_Draft_Assemblies.fa' reference_weights='2'), or separated (e.g Option 2 - references='A.fa B.fa' reference_weights='2 2')?

We have done these tests and the results are quite different.
Option 1 - components in graph: 1698 ; 73mb of 815mb assigned.scaffolds (improve of n50, 200kb) .
Option 2 - components in graph: 922 ; 47mb of 815mb assigned.scaffolds (improve of n50, 100kb) .

Are the low values of the assigned.scaffolds expected ?

"We find ntJoin to work better when running iteratively, as opposed to providing multiple references. This is because there may exist conflicts between the provided references that prevent unambiguous joins."

By running interactively, do you mean 1st run the target genome against the reference A,  2º  run the previous output against reference B ... etc?   Regarding the "no_cut" paremeter, Do you recommend to use it between each interaction ?

André

**Comment by warrenlr** [comment] 2021-02-01 16:05
Hi André,

```RAILS/Cobbler: break input assemblies into overlapping 2500, 5000 and 10000 bp sequences" means to merge all assemblies and collect all sequences of 2500, 50000, 10000 to three independent files, or really break the contigs in sub-sequences of 2500, 50000, 10000 and run them (pooled or interactively) against the reference ?```

The latter. Use scripts to break your assemblies into overlapping sequence "chunks" of various small/med/large sizes and use as input to fill gap (refer to the RAILS/Cobbler JOSS manuscript). You can submit them all at once if you'd like, since the gap sequence is derived from the best set of alignment (having the most support).

For any other non-LINKS questions, I strongly encourage you to open an issue/question on the specific github project. This way your questions would likely get more visibility such that our developers can be assist you (and the question(s) would likely be pertinent to other users).

Thank you
Rene

**Closed by warrenlr** 2021-02-01 16:05 UTC
Labels: question
